### ISSUE TITLE
dw_init response

### ISSUE THREAD

**Issue by beretta42** [vandys/pydw#1]
I don't think the intent of dw4 spec is to echo what the client sends.  The official dw4 server returns 0x00.  [lwwire](http://lwwire.projects.l-w.ca/hg/) returns 0x80.  The argument that the client sends informs the server of the client's abilities.  Not much comes of this, of course.  (sending 0x42 to the server will in-fact shut down it's "hdbdos translation mode" setting - other than that I'm not sure!)

**Comment by vandys** [comment]
The spec I had in hand provided no details, and I didn't see the MAME client caring, so
I just picked an answer out of the hat.  I'll change it to 0.  Thanks!
